title: Min J Bio
author: Minjae Cho
email: ussr1285@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Minjae Cho
  tagline: Actually I'm Minjae Joe.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false
  disqus_shortname: games # 잠시만
  analytics_id : '113361760' # 구글 애널리틱스

  # generate social links in footer
  social_links:
  #  twitter: 
    github:  ussr1285
    facebook: MinjaeFace
    instagram: mininstar5313
  #  linkedIn: in/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed